@hostname = localhost
@port = 5000
@host = {{hostname}}:{{port}}
@contentType = application/json

@email = joe@smith.com
@password = joepassword

# GET Courses
# Expected Result: List of courses
GET http://{{host}}/api/courses HTTP/1.1
Host: {{host}}
Accept: {{contentType}}

###

# GET Course
# Expected result: data for course
@id = 1

GET http://{{host}}/api/courses/{{id}} HTTP/1.1
Host: {{host}}
Accept: {{contentType}}


###

# GET Course - Non-existent ID
# Expected result: 404
@unusedId = 101010

GET http://{{host}}/api/courses/{{unusedId}} HTTP/1.1
Host: {{host}}
Accept: {{contentType}}

###

# POST Course - No auth
# Expected result: 401
POST http://{{host}}/api/courses HTTP/1.1
Host: {{host}}
Accept: {{contentType}}
Content-Type: {{contentType}}

{}

###

# POST Course - Empty data
# Expected result: 400
POST http://{{host}}/api/courses HTTP/1.1
Host: {{host}}
Authorization: Basic {{email}} {{password}}
Accept: {{contentType}}
Content-Type: {{contentType}}

{}

###

# POST Course - Minimal data
# Expected result: Created course
POST http://{{host}}/api/courses HTTP/1.1
Host: {{host}}
Authorization: Basic {{email}} {{password}}
Accept: {{contentType}}
Content-Type: {{contentType}}

{
  "title": "Test Course 1",
  "description": "Test Course 1 description"
}

###

# PUT Course - No auth
# Expected result: 401
PUT http://{{host}}/api/courses/4 HTTP/1.1
Host: {{host}}
Accept: {{contentType}}
Content-Type: {{contentType}}

{}

###

@email2 = sally@jones.com
@password2 = sallypassword

# PUT Course - Auth with different user than course creator
# Expected result: 403
PUT http://{{host}}/api/courses/4 HTTP/1.1
Host: {{host}}
Accept: {{contentType}}
Content-Type: {{contentType}}
Authorization: Basic {{email2}} {{password2}}

{}

###

# PUT Course - Empty body
# Expected result: 400
PUT http://{{host}}/api/courses/4 HTTP/1.1
Host: {{host}}
Accept: {{contentType}}
Content-Type: {{contentType}}
Authorization: Basic {{email}} {{password}}

{}

###

# PUT Course - Minimal body
# Expected result: 204
PUT http://{{host}}/api/courses/4 HTTP/1.1
Host: {{host}}
Accept: {{contentType}}
Content-Type: {{contentType}}
Authorization: Basic {{email}} {{password}}

{
  "title": "Test Course 1, 2nd edition",
  "description": "Updated course description"
}

###


# PUT Course - Nonexistent course
# Expected result: 404
PUT http://{{host}}/api/courses/{{unusedId}} HTTP/1.1
Host: {{host}}
Accept: {{contentType}}
Content-Type: {{contentType}}
Authorization: Basic {{email}} {{password}}

{
  "title": "Test Course 1, 2nd edition",
  "description": "Updated course description"
}

###

# DELETE Course - No auth
# Expected result: 401
DELETE http://{{host}}/api/courses/4 HTTP/1.1
Host: {{host}}
Accept: {{contentType}}

###

# DELETE Course - Auth with different user than course creator
# Expected result: 403
DELETE http://{{host}}/api/courses/4 HTTP/1.1
Host: {{host}}
Accept: {{contentType}}
Authorization: Basic {{email2}} {{password2}}

###

# DELETE Course - Valid Auth
# Expected result: 204
DELETE http://{{host}}/api/courses/4 HTTP/1.1
Host: {{host}}
Accept: {{contentType}}
Authorization: Basic {{email}} {{password}}

###

# DELETE Course - Nonexistent course
# Expected result: 404
DELETE http://{{host}}/api/courses/{{unusedId}} HTTP/1.1
Host: {{host}}
Accept: {{contentType}}
Authorization: Basic {{email}} {{password}}
